### ISSUE TITLE
AttributeError: 'module' object has no attribute 'qsize'

### ISSUE THREAD

**Issue by supriya-gdptl** [marinkaz/ohmnet#1]
Hello @marinkaz 
Thank you for sharing the code.
 I am trying to run it on the given data of brain tissue-specific protein interaction network.
I got following error when I executed ` python2.7 main.py --input "data/brain.list" --outdir "tmp" --hierarchy "data/brain.hierarchy"`

`INFO:ohmnet.gensimmod.model.word2vec:training model with 8 workers on 16897 vocabulary and 128 features, using sg=1 hs=0 sample=0.001 negative=5 window=10`

`INFO:ohmnet.gensimmod.model.word2vec:expecting 84485 sentences, matching count from corpus used for vocabulary survey`
`Processing: 0/100`
`Processing: 0/100`
`Processing: 0/100`
`Processing: 0/100`
`Processing: 0/100`
`Processing: 0/100`
`Processing: 0/100`
 `Processing: 0/100`
`Processing: 0/100`
`Traceback (most recent call last):`
  `File "main.py", line 66, in <module>`
    `main(args)`
`  File "main.py", line 62, in main`
    `on.embed_multilayer()`
 ` File "ohmnet/ohmnet/ohmnet.py", line 197, in embed_multilayer`
    `workers=self.n_workers, iter=1, batch_words=pushed_examples)`
  `File "ohmnet/ohmnet/gensimmod/model/word2vec.py", line 416, in __init__`
    `self.train(sentences)`
  `File "ohmnet/ohmnet/gensimmod/model/word2vec.py", line 853, in train`
    `utils.qsize(job_queue), utils.qsize(progress_queue))`
`AttributeError: 'module' object has no attribute 'qsize'`

Could you please help in resolving this error?

Thanks,
Supriya

**Comment by marinkaz** [comment]
Thanks! Fixed.
